# Production version
prod:
  # Don't use Minio, connect to S3
  # The 'reproserver-secret-prod' secret needs to have 's3_key' and 's3_secret'
  use_minio: false
  # Possible are 'true', 'false' or a PersistentVolumeClaim name
  postgres_volume: true
  postgres_database: reproserver
  # Images will be pulled from that registry, eg vidanyu/reproserver-web:0.4
  image_registry: "vidanyu"
  # This can be overridden on the command-line, `doit k8s tier=prod tag=0.3`
  tag: 0.4
  # Period for the Kubernetes liveness checks
  liveness_probe_period_seconds: 60

# Development environment, no persistence
dev:
  # Use Minio, and store all data in the containers
  use_minio: true
  minio_volume: false
  postgres_volume: false
  # Period for the Kubernetes liveness checks
  liveness_probe_period_seconds: 60
  # Don't run the init job
  init_job: false
