version: "2"
volumes:
  rabbit-data:
  minio-data:
services:
  rabbitmq:
    image: "rabbitmq:3.6.9-management"
    container_name: rs-rabbit
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: hackme
    ports:
      - "8080:15672"
  web:
    build: web
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
  builder:
    build: builder
    depends_on:
      - rabbitmq
  runner:
    build: runner
    depends_on:
      - rabbitmq
  registry:
    image: "registry:2.6"
  minio:
    image: "minio/minio:RELEASE.2017-04-29T00-40-27Z"
    volumes:
      - minio-data:/export
    command: server /export
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: hackmehackme
    ports:
      - "9000:9000"
