# Generated by Django 2.1.2 on 2018-12-21 02:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildLogLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 3, 13, 323103, tzinfo=utc))),
                ('line', models.TextField()),
            ],
            options={
                'db_table': 'build_logs',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('hash', models.TextField(primary_key=True, serialize=False)),
                ('status', models.TextField(default='1')),
                ('docker_image', models.TextField(null=True)),
                ('last_access', models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 3, 13, 307724, tzinfo=utc))),
                ('log', models.ManyToManyField(related_name='_experiment_log_+', to='web.BuildLogLine')),
            ],
            options={
                'db_table': 'experiments',
            },
        ),
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField()),
                ('name', models.TextField()),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'input_files',
            },
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField()),
                ('name', models.TextField()),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'output_files',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('optional', models.BooleanField()),
                ('default', models.TextField(null=True)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Experiment')),
                ('experiment_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Experiment')),
            ],
            options={
                'db_table': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'run_parameters',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_input', models.BooleanField()),
                ('is_output', models.BooleanField()),
                ('name', models.TextField()),
                ('path', models.TextField()),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Experiment')),
                ('experiment_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Experiment')),
            ],
            options={
                'db_table': 'paths',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 3, 13, 317721, tzinfo=utc))),
                ('started', models.DateField(null=True)),
                ('done', models.DateField(null=True)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Experiment')),
                ('experiment_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Experiment')),
                ('input_files', models.ManyToManyField(related_name='_run_input_files_+', to='web.InputFile')),
            ],
            options={
                'db_table': 'runs',
            },
        ),
        migrations.CreateModel(
            name='RunLogLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 3, 13, 324060, tzinfo=utc))),
                ('line', models.TextField()),
                ('run_RunLogLineß', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Run')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Run')),
            ],
            options={
                'db_table': 'run_logs',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('submitted_ip', models.TextField(null=True)),
                ('provider_key', models.TextField(db_index=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 3, 13, 314519, tzinfo=utc))),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Experiment')),
                ('experiment_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Experiment', unique='True')),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.AddField(
            model_name='run',
            name='log',
            field=models.ManyToManyField(related_name='_run_log_+', to='web.RunLogLine'),
        ),
        migrations.AddField(
            model_name='run',
            name='output_files',
            field=models.ManyToManyField(related_name='_run_output_files_+', to='web.OutputFile'),
        ),
        migrations.AddField(
            model_name='run',
            name='parameter_values',
            field=models.ManyToManyField(related_name='_run_parameter_values_+', to='web.ParameterValue'),
        ),
        migrations.AddField(
            model_name='run',
            name='upload_Run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Upload'),
        ),
        migrations.AddField(
            model_name='run',
            name='upload_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web.Upload'),
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Run'),
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='run_parameterValue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Run'),
        ),
        migrations.AddField(
            model_name='outputfile',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Run'),
        ),
        migrations.AddField(
            model_name='outputfile',
            name='run_outputFile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Run'),
        ),
        migrations.AddField(
            model_name='inputfile',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Run'),
        ),
        migrations.AddField(
            model_name='inputfile',
            name='run_inputFile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Run'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='parameters',
            field=models.ManyToManyField(related_name='_experiment_parameters_+', to='web.Parameter'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='paths',
            field=models.ManyToManyField(related_name='_experiment_paths_+', to='web.Path'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='runs',
            field=models.ManyToManyField(related_name='_experiment_runs_+', to='web.Run'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='uploads',
            field=models.ManyToManyField(related_name='_experiment_uploads_+', to='web.Upload'),
        ),
        migrations.AddField(
            model_name='buildlogline',
            name='experiment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Experiment'),
        ),
        migrations.AddField(
            model_name='buildlogline',
            name='experiment_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Experiment'),
        ),
    ]
