# Generated by Django 2.1.2 on 2018-12-21 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181221_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 10, 7, 175907, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 10, 7, 156748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 10, 7, 169247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 10, 7, 176996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 10, 7, 165478, tzinfo=utc)),
        ),
    ]
