# Generated by Django 2.1.2 on 2018-12-21 02:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181221_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 21, 23, 22008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 21, 22, 995838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 21, 23, 14216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 21, 23, 23519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 2, 21, 23, 9357, tzinfo=utc)),
        ),
    ]
