# Generated by Django 2.1.2 on 2018-12-21 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20181221_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='experiment_hash',
        ),
        migrations.AlterField(
            model_name='buildlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 5, 41, 39, 491197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 5, 41, 39, 475828, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 5, 41, 39, 485628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 5, 41, 39, 492202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 5, 41, 39, 482589, tzinfo=utc)),
        ),
    ]
