# Generated by Django 2.1.2 on 2018-12-21 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181221_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildlogline',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='path',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='run',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='experiment',
        ),
        migrations.AddField(
            model_name='upload',
            name='experiment_hash',
            field=models.ForeignKey(default=datetime.datetime(2018, 12, 21, 6, 54, 58, 987704, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.Experiment', unique='True'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 6, 54, 39, 769274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 6, 54, 39, 754697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 6, 54, 39, 764005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 6, 54, 39, 770437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 6, 54, 39, 761354, tzinfo=utc)),
        ),
    ]
