# Generated by Django 2.1.2 on 2018-12-21 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20181221_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 9, 48, 14, 801533, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 9, 48, 14, 787159, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='run',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 9, 48, 14, 796285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runlogline',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 9, 48, 14, 802403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='upload',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 9, 48, 14, 793638, tzinfo=utc)),
        ),
    ]
